HOST = "localhost:31415"
#HOST = "etree.linkedmusic.org:31415"
ENDPOINT="http://localhost:3030/etree/sparql"
#ENDPOINT="http://etree.linkedmusic.org/sparql"
#ENDPOINT="http://euterpe.oerc.ox.ac.uk/sparql"
